<a href="https://colab.research.google.com/github/19PA1A04B9/-10-03-2020/blob/master/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd # for handling data in the form of tables
import numpy as np # For handling matrix
from sklearn.model_selection import train_test_split # For spliting the data into train and test
from sklearn import metrics # for calculation of accuracy and precision
from sklearn.metrics import confusion_matrix #
from sklearn import svm

In [6]:
ipl=pd.read_csv("Iris.csv")
ipl

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [7]:
print(ipl.dtypes)

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object


In [8]:
ipl.describe(include="all")

Id  SepalLengthCm  ...  PetalWidthCm         Species
count   150.000000     150.000000  ...    150.000000             150
unique         NaN            NaN  ...           NaN               3
top            NaN            NaN  ...           NaN  Iris-virginica
freq           NaN            NaN  ...           NaN              50
mean     75.500000       5.843333  ...      1.198667             NaN
std      43.445368       0.828066  ...      0.763161             NaN
min       1.000000       4.300000  ...      0.100000             NaN
25%      38.250000       5.100000  ...      0.300000             NaN
50%      75.500000       5.800000  ...      1.300000             NaN
75%     112.750000       6.400000  ...      1.800000             NaN
max     150.000000       7.900000  ...      2.500000             NaN

[11 rows x 6 columns]

In [9]:
ipl.isna().any() # to find NA's

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [10]:
print("Features: ", ipl.columns)# features name in dataset

Features:  Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')


In [0]:
X=ipl[['PetalLengthCm','PetalWidthCm','SepalLengthCm','SepalWidthCm']].values #selection of features

y= ipl['Species'].values# selsction of targetvariables

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42) #spillting of data into train and test parts

In [13]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[1.  0.2 4.6 3.6]
 [1.5 0.4 5.7 4.4]
 [4.4 1.4 6.7 3.1]
 [1.6 0.2 4.8 3.4]
 [1.3 0.2 4.4 3.2]
 [5.  1.9 6.3 2.5]
 [4.5 1.5 6.4 3.2]
 [1.5 0.2 5.2 3.5]
 [1.4 0.2 5.  3.6]
 [1.5 0.1 5.2 4.1]
 [5.1 1.9 5.8 2.7]
 [4.5 1.6 6.  3.4]
 [4.7 1.5 6.7 3.1]
 [1.3 0.4 5.4 3.9]
 [1.5 0.2 5.4 3.7]
 [3.7 1.  5.5 2.4]
 [5.1 1.5 6.3 2.8]
 [5.5 1.8 6.4 3.1]
 [4.4 1.4 6.6 3. ]
 [6.1 2.5 7.2 3.6]
 [4.2 1.3 5.7 2.9]
 [6.6 2.1 7.6 3. ]
 [4.5 1.5 5.6 3. ]
 [1.4 0.2 5.1 3.5]
 [6.7 2.  7.7 2.8]
 [4.1 1.  5.8 2.7]
 [1.4 0.2 5.2 3.4]
 [1.3 0.3 5.  3.5]
 [1.9 0.4 5.1 3.8]
 [3.5 1.  5.  2. ]
 [4.9 1.8 6.3 2.7]
 [1.9 0.2 4.8 3.4]
 [1.6 0.2 5.  3. ]
 [1.7 0.5 5.1 3.3]
 [4.2 1.3 5.6 2.7]
 [1.5 0.2 5.1 3.4]
 [4.2 1.2 5.7 3. ]
 [6.7 2.2 7.7 3.8]
 [1.4 0.2 4.6 3.2]
 [4.3 1.3 6.2 2.9]
 [5.  2.  5.7 2.5]
 [1.4 0.2 5.5 4.2]
 [4.8 1.8 6.  3. ]
 [5.1 1.9 5.8 2.7]
 [4.  1.  6.  2.2]
 [4.5 1.5 5.4 3. ]
 [5.4 2.3 6.2 3.4]
 [4.  1.3 5.5 2.3]
 [1.7 0.4 5.4 3.9]
 [3.3 1.  5.  2.3]
 [5.3 1.9 6.4 2.7]
 [1.4 0.2 5.  3.3]
 [1.2 0.2 5.

In [0]:
clf = svm.SVC(kernel='linear') #declaring a variablr to svm model

In [15]:
clf.fit(X_train, y_train)#fitting data set into svm model

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
y_pred = clf.predict(X_test)#now testing our model
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [17]:
#confusion matrix creating
cm = np.array(confusion_matrix(y_test, y_pred))
df_cm = pd.DataFrame(cm, columns=np.unique(y_pred), index = np.unique(y_test))
df_cm.index.name = 'Actual'
df_cm.columns.name = 'Predicted'
print(df_cm)

Predicted        Iris-setosa  Iris-versicolor  Iris-virginica
Actual                                                       
Iris-setosa               10                0               0
Iris-versicolor            0                9               0
Iris-virginica             0                0              11


In [18]:
#calculation of accuracy of our model
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [19]:
#calculation of precision of  our model
print("Precision:",metrics.precision_score(y_test, y_pred,average="macro"))

Precision: 1.0
